### ISSUE TITLE
After cloning, products failing to render and error status code 500

### ISSUE THREAD

**Issue by Bruttix** [irenemmassy/Full-SorceCode-ShoeShop-Ecommerce-Web#1]
Clone -> change directory to ShoeShop/client_frontend/ and npm install 
-> then cd ../server npm install bcryptjs dotenv express express-async-handler jsonwebtoken mongoose morgan npm install -D concurrently nodemon 

-> then cd ../client_frontend/ and npm start which then examining localhost:3000 , **"Request failed with status code 500"** is displayed where products would normally be displayed. **Error message in console :** 
"Warning: Invalid DOM property `class`. Did you mean `className`?
    at i
    at button
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at Header (http://localhost:3000/static/js/main.chunk.js:2938:87)
    at div
    at HomeScreen (http://localhost:3000/static/js/main.chunk.js:6121:5)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:44984:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:45186:29)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:44615:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:42601:35)
    at App
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:40109:20)
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
validateProperty$1 @ react-dom.development.js:3505
warnUnknownProperties @ react-dom.development.js:3559
validateProperties$2 @ react-dom.development.js:3583
validatePropertiesInDevelopment @ react-dom.development.js:8765
setInitialProperties @ react-dom.development.js:9041
finalizeInitialChildren @ react-dom.development.js:10201
completeWork @ react-dom.development.js:19470
completeUnitOfWork @ react-dom.development.js:22815
performUnitOfWork @ react-dom.development.js:22787
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
(anonymous) @ index.js:7
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ SingleProduct.js:217
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
xhr.js:210          GET http://localhost:3000/api/products?keyword=%20&pageNumber= 500 (Internal Server Error)"

**Comment by Bruttix** [comment]
Also ( i did add .env with PORT = NODE_ENV JWT_SECRET PAYPAL_CLIENT_ID MONGO_URL properties set )

**Comment by Bruttix** [comment]
fixed by running both npm start in both server & frontend
